import type { TypegenConfig } from '../config'
import type { EnvVar } from './dotenv'

export const LAZY_TS_CONTENT = `export function defineLazyProperty<T>(
  target: object,
  property: string,
  getter: () => T,
) {
  const value = getter()
  Object.defineProperty(target, property, { value })
  return value
}

export function lazy<T>(getter: () => T): { value: T } {
  return {
    get value() {
      return defineLazyProperty(this, 'value', getter)
    },
  }
}
`

const GENERATED_HEADER = [
	'// This file is auto-generated by env. Do not edit.',
	'// See references/env.md for usage and workflow.',
	'',
].join('\n')

/**
 * 生成 TypeScript 类型定义
 */
export function generateTypes(vars: EnvVar[], config: TypegenConfig): string {
	const publicVars = vars.filter((v) => v.scope === 'public')
	const privateVars = vars.filter((v) => v.scope === 'private')

	const schema = config.schema ?? 'valibot'

	if (schema === 'none') {
		return generatePlainTypes(publicVars, privateVars)
	}

	if (schema === 'zod') {
		return generateZodTypes(publicVars, privateVars)
	}

	return generateValibotTypes(publicVars, privateVars)
}

function generateValibotTypes(
	publicVars: EnvVar[],
	privateVars: EnvVar[],
): string {
	const lines: string[] = [
		GENERATED_HEADER,
		"import * as v from 'valibot'",
		"import { lazy } from './lazy'",
		'',
	]

	// Public schema
	lines.push('export const publicEnvSchema = v.object({')
	for (const v of publicVars) {
		const validator = inferValidator(v.key, v.value, 'valibot')
		lines.push(`  ${v.key}: ${validator},`)
	}
	lines.push('})')
	lines.push('')

	// Private schema
	lines.push('export const privateEnvSchema = v.object({')
	for (const v of privateVars) {
		const validator = inferValidator(v.key, v.value, 'valibot')
		lines.push(`  ${v.key}: ${validator},`)
	}
	lines.push('})')
	lines.push('')

	// Merged schema
	lines.push('export const envSchema = v.object({')
	lines.push('  ...publicEnvSchema.entries,')
	lines.push('  ...privateEnvSchema.entries,')
	lines.push('})')
	lines.push('')

	// Types
	lines.push('export type PublicEnv = v.InferOutput<typeof publicEnvSchema>')
	lines.push('export type PrivateEnv = v.InferOutput<typeof privateEnvSchema>')
	lines.push('export type Env = v.InferOutput<typeof envSchema>')
	lines.push('')

	// Lazy env
	lines.push('export const env$ = lazy(() => v.parse(envSchema, process.env))')
	lines.push('')

	lines.push(...generateEnvDtsHint())

	return lines.join('\n')
}

function generateZodTypes(publicVars: EnvVar[], privateVars: EnvVar[]): string {
	const lines: string[] = [
		GENERATED_HEADER,
		"import { z } from 'zod'",
		"import { lazy } from './lazy'",
		'',
	]

	// Public schema
	lines.push('export const publicEnvSchema = z.object({')
	for (const v of publicVars) {
		const validator = inferValidator(v.key, v.value, 'zod')
		lines.push(`  ${v.key}: ${validator},`)
	}
	lines.push('})')
	lines.push('')

	// Private schema
	lines.push('export const privateEnvSchema = z.object({')
	for (const v of privateVars) {
		const validator = inferValidator(v.key, v.value, 'zod')
		lines.push(`  ${v.key}: ${validator},`)
	}
	lines.push('})')
	lines.push('')

	// Merged schema
	lines.push('export const envSchema = publicEnvSchema.merge(privateEnvSchema)')
	lines.push('')

	// Types
	lines.push('export type PublicEnv = z.infer<typeof publicEnvSchema>')
	lines.push('export type PrivateEnv = z.infer<typeof privateEnvSchema>')
	lines.push('export type Env = z.infer<typeof envSchema>')
	lines.push('')

	// Lazy env
	lines.push('export const env$ = lazy(() => envSchema.parse(process.env))')
	lines.push('')

	lines.push(...generateEnvDtsHint())

	return lines.join('\n')
}

function generatePlainTypes(
	publicVars: EnvVar[],
	privateVars: EnvVar[],
): string {
	const lines: string[] = [GENERATED_HEADER]

	lines.push('export type PublicEnv = {')
	for (const v of publicVars) {
		lines.push(`  ${v.key}: string`)
	}
	lines.push('}')
	lines.push('')

	lines.push('export type PrivateEnv = {')
	for (const v of privateVars) {
		lines.push(`  ${v.key}: string`)
	}
	lines.push('}')
	lines.push('')

	lines.push(...generateEnvDtsHint())

	return lines.join('\n')
}

function generateEnvDtsHint(): string[] {
	return [
		'// env.d.ts',
		'// import type { PrivateEnv, PublicEnv } from "@/lib/env"',
		'// declare global {',
		'//',
		'//   namespace NodeJS {',
		'//     interface ProcessEnv extends PublicEnv, PrivateEnv {}',
		'//   }',
		'//',
		'//   interface ImportMetaEnv extends PublicEnv {}',
		'// }',
		'',
	]
}

function inferValidator(
	key: string,
	value: string,
	lib: 'valibot' | 'zod',
): string {
	const lowerKey = key.toLowerCase()

	// URL pattern
	if (lowerKey.includes('url') || lowerKey.includes('endpoint')) {
		return lib === 'valibot'
			? 'v.pipe(v.string(), v.url())'
			: 'z.string().url()'
	}

	// Default to string
	return lib === 'valibot' ? 'v.string()' : 'z.string()'
}
